In [5]:
#1 write a NumPy program to create a element-wise comparison(greater,greater_equal,less and less_equal) of two given arrays.
import numpy as np
x=np.array([4,5,7,8,9])
y=np.array([5,9,7,5,3])
print("Greater")
print(np.greater(x,y))
print('Greater_Equal')
print(np.greater_equal(x,y))
print('Less')
print(np.less(x,y))
print('Less_eqaul')
print(np.less_equal(x,y))


Greater
[False False False  True  True]
Greater_Equal
[False False  True  True  True]
Less
[ True  True False False False]
Less_eqaul
[ True  True  True False False]


In [8]:
#2 write a Numpy program to create an array of all the even integers from 30 to 70.
import numpy as np
x=np.arange(30,71,2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [10]:
#3 write a Numpy program to create a 3x3 identity matrix.
import numpy as np
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#4 write a numpy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
import numpy as np
x=np.arange(0,21)
print('Before')
print(x)
x[(x>=9) & (x<=15)]*=-1
print('After')
print(x)



Before
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [23]:
#5 write a numpy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1,2,3,4,5.
import numpy as np
x=np.arange(1,6)
y=np.diag(x)
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [32]:
#6 write a numpy program to compute sum of all elements,sum of each column and sum of each row of a given array.
import numpy as np
x=np.matrix('1 2 3; 4 5 6;7 8 9')
print(x)
print(' total sum')
print(x.sum())
print('sum of each column')
print(np.sum(x,axis=0))
print('sum of each row')
print(np.sum(x,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 total sum
45
sum of each column
[[12 15 18]]
sum of each row
[[ 6]
 [15]
 [24]]


In [38]:
#7 write a numpy program to save a given array to a text file and load it.
import numpy as np
x=np.arange(1,10).reshape(3,3)
print('original array')
print(x)
header='col1 col2 col3'
np.savetxt("temp.txt",x,fmt="%d",header=header)
print("After loading text")
result=np.loadtxt('temp.txt')
print(result)




original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After loading text
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [40]:
#8 write a numpy program to check whether two arrays are equal(element wise) or not.
import numpy as np
x=np.matrix('4 5 6;7 8 9;2 2 3')
y=np.matrix('4 8 6;7 9 8;2 3 2')
print(np.equal(x,y))

[[ True False  True]
 [ True False False]
 [ True False False]]


In [45]:
#9 write a numpy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows
x=np.arange(16).reshape(4,4)
print('Before swapping')
print(x)
x[[0,-1],:]=x[[-1,0],:]
print('After Swapping')
print(x)

Before swapping
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After Swapping
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [6]:
#10 write a numpy program to multiply two given arrays of same size element by element.
import numpy as np
x=np.array([4,5,6,7])
y=np.array([7,8,9,7])
print(np.multiply(x,y))

[28 40 54 49]
